name = "Lok"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "0a9a707c-a762-5221-5069-adfc0a28ca57"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
